version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    labels:
      - dependencies
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      patch-upgrades:
        update-types: ["patch"]
    ignore:
      - dependency-name: "*"
        update-types:
          ["version-update:semver-major", "version-update:semver-minor"]
    labels:
      - dependencies
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    labels:
      - dependencies
